[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zohar_token = "3AQuvQXzEM1vqNmRxH5z1M2gPcaTtqp1bh2WSSnY8L6L"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
